// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type CacheListCachesRequest struct {
	// Tigris project name
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type CacheListCachesResponse struct {
	ContentType string
	// OK
	ListCachesResponse *shared.ListCachesResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
