// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type CacheDelRequest struct {
	DelRequest shared.DelRequest `request:"mediaType=application/json"`
	// cache key
	Key string `pathParam:"style=simple,explode=false,name=key"`
	// cache name
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Tigris project name
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type CacheDelResponse struct {
	ContentType string
	// OK
	DelResponse *shared.DelResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
