// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type CacheKeysRequest struct {
	// optional - count of keys to return a stream response line.
	Count *int64 `queryParam:"style=form,explode=true,name=count"`
	// optional - cursor - skip this argument if no cursor is associated
	Cursor *int64 `queryParam:"style=form,explode=true,name=cursor"`
	// cache name
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// optional key pattern
	Pattern *string `queryParam:"style=form,explode=true,name=pattern"`
	// Tigris project name
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type CacheKeysResponse struct {
	ContentType string
	// OK
	KeysResponse *shared.KeysResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
