// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type CacheListCachesRequest struct {
	// Tigris project name
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *CacheListCachesRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type CacheListCachesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ListCachesResponse *shared.ListCachesResponse
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CacheListCachesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CacheListCachesResponse) GetListCachesResponse() *shared.ListCachesResponse {
	if o == nil {
		return nil
	}
	return o.ListCachesResponse
}

func (o *CacheListCachesResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CacheListCachesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CacheListCachesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
