// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type ManagementInsertNamespaceMetadataRequest struct {
	InsertNamespaceMetadataRequest shared.InsertNamespaceMetadataRequest `request:"mediaType=application/json"`
	MetadataKey                    string                                `pathParam:"style=simple,explode=false,name=metadataKey"`
}

func (o *ManagementInsertNamespaceMetadataRequest) GetInsertNamespaceMetadataRequest() shared.InsertNamespaceMetadataRequest {
	if o == nil {
		return shared.InsertNamespaceMetadataRequest{}
	}
	return o.InsertNamespaceMetadataRequest
}

func (o *ManagementInsertNamespaceMetadataRequest) GetMetadataKey() string {
	if o == nil {
		return ""
	}
	return o.MetadataKey
}

type ManagementInsertNamespaceMetadataResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	InsertNamespaceMetadataResponse *shared.InsertNamespaceMetadataResponse
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ManagementInsertNamespaceMetadataResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ManagementInsertNamespaceMetadataResponse) GetInsertNamespaceMetadataResponse() *shared.InsertNamespaceMetadataResponse {
	if o == nil {
		return nil
	}
	return o.InsertNamespaceMetadataResponse
}

func (o *ManagementInsertNamespaceMetadataResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *ManagementInsertNamespaceMetadataResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ManagementInsertNamespaceMetadataResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
