// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type RealtimeGetRTChannelsRequest struct {
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type RealtimeGetRTChannelsResponse struct {
	ContentType string
	// OK
	GetRTChannelsResponse *shared.GetRTChannelsResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
