// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchSearchRequest struct {
	SearchIndexRequest shared.SearchIndexRequest `request:"mediaType=application/json"`
	// The index name to search documents from.
	Index string `pathParam:"style=simple,explode=false,name=index"`
	// Project name whose db is under target to search documents from.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type SearchSearchResponse struct {
	ContentType string
	// OK
	SearchIndexResponse *shared.SearchIndexResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
