// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchUpdateRequest struct {
	UpdateDocumentRequest shared.UpdateDocumentRequest `request:"mediaType=application/json"`
	// Index name where to create documents.
	Index string `pathParam:"style=simple,explode=false,name=index"`
	// Project name whose db is under target to insert documents.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *SearchUpdateRequest) GetUpdateDocumentRequest() shared.UpdateDocumentRequest {
	if o == nil {
		return shared.UpdateDocumentRequest{}
	}
	return o.UpdateDocumentRequest
}

func (o *SearchUpdateRequest) GetIndex() string {
	if o == nil {
		return ""
	}
	return o.Index
}

func (o *SearchUpdateRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type SearchUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	UpdateDocumentResponse *shared.UpdateDocumentResponse
}

func (o *SearchUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchUpdateResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *SearchUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *SearchUpdateResponse) GetUpdateDocumentResponse() *shared.UpdateDocumentResponse {
	if o == nil {
		return nil
	}
	return o.UpdateDocumentResponse
}
