// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchListIndexesRequest struct {
	// Applicable only in case index is backed by Tigris collection. This is the database branch for the above collection. For primary database it can be omitted or "main" can be passed.
	Branch *string `queryParam:"style=form,explode=true,name=filter.branch"`
	// Applicable only in case index is backed by Tigris collection.
	Collection *string `queryParam:"style=form,explode=true,name=filter.collection"`
	// An index can be either managed by user explicitly then the type is set as "user" or the index is backed by Tigris collection. In case it is backed by Tigris collection the type is "tigris".
	Type *string `queryParam:"style=form,explode=true,name=filter.type"`
	// Tigris project name.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *SearchListIndexesRequest) GetBranch() *string {
	if o == nil {
		return nil
	}
	return o.Branch
}

func (o *SearchListIndexesRequest) GetCollection() *string {
	if o == nil {
		return nil
	}
	return o.Collection
}

func (o *SearchListIndexesRequest) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *SearchListIndexesRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type SearchListIndexesResponse struct {
	ContentType string
	// OK
	ListIndexesResponse *shared.ListIndexesResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}

func (o *SearchListIndexesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchListIndexesResponse) GetListIndexesResponse() *shared.ListIndexesResponse {
	if o == nil {
		return nil
	}
	return o.ListIndexesResponse
}

func (o *SearchListIndexesResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *SearchListIndexesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchListIndexesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
