// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchCreateOrUpdateIndexRequest struct {
	CreateOrUpdateIndexRequest shared.CreateOrUpdateIndexRequest `request:"mediaType=application/json"`
	// search index name.
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Tigris project name.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type SearchCreateOrUpdateIndexResponse struct {
	ContentType string
	// OK
	CreateOrUpdateIndexResponse *shared.CreateOrUpdateIndexResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
