// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchCreateOrUpdateIndexRequest struct {
	CreateOrUpdateIndexRequest shared.CreateOrUpdateIndexRequest `request:"mediaType=application/json"`
	// search index name.
	Name string `pathParam:"style=simple,explode=false,name=name"`
	// Tigris project name.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *SearchCreateOrUpdateIndexRequest) GetCreateOrUpdateIndexRequest() shared.CreateOrUpdateIndexRequest {
	if o == nil {
		return shared.CreateOrUpdateIndexRequest{}
	}
	return o.CreateOrUpdateIndexRequest
}

func (o *SearchCreateOrUpdateIndexRequest) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SearchCreateOrUpdateIndexRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type SearchCreateOrUpdateIndexResponse struct {
	ContentType string
	// OK
	CreateOrUpdateIndexResponse *shared.CreateOrUpdateIndexResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}

func (o *SearchCreateOrUpdateIndexResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchCreateOrUpdateIndexResponse) GetCreateOrUpdateIndexResponse() *shared.CreateOrUpdateIndexResponse {
	if o == nil {
		return nil
	}
	return o.CreateOrUpdateIndexResponse
}

func (o *SearchCreateOrUpdateIndexResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *SearchCreateOrUpdateIndexResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchCreateOrUpdateIndexResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
