// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchGetRequest struct {
	// document id.
	Ids []string `queryParam:"style=form,explode=true,name=ids"`
	// index name where to create documents.
	Index string `pathParam:"style=simple,explode=false,name=index"`
	// Tigris project name.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *SearchGetRequest) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}

func (o *SearchGetRequest) GetIndex() string {
	if o == nil {
		return ""
	}
	return o.Index
}

func (o *SearchGetRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type SearchGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	GetDocumentResponse *shared.GetDocumentResponse
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SearchGetResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SearchGetResponse) GetGetDocumentResponse() *shared.GetDocumentResponse {
	if o == nil {
		return nil
	}
	return o.GetDocumentResponse
}

func (o *SearchGetResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *SearchGetResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SearchGetResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
