// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type SearchGetRequest struct {
	// document id.
	Ids []string `queryParam:"style=form,explode=true,name=ids"`
	// index name where to create documents.
	Index string `pathParam:"style=simple,explode=false,name=index"`
	// Tigris project name.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type SearchGetResponse struct {
	ContentType string
	// OK
	GetDocumentResponse *shared.GetDocumentResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
