// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisCreateProjectRequest struct {
	CreateProjectRequest shared.CreateProjectRequest `request:"mediaType=application/json"`
	// Create project with this name.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *TigrisCreateProjectRequest) GetCreateProjectRequest() shared.CreateProjectRequest {
	if o == nil {
		return shared.CreateProjectRequest{}
	}
	return o.CreateProjectRequest
}

func (o *TigrisCreateProjectRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type TigrisCreateProjectResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	CreateProjectResponse *shared.CreateProjectResponse
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *TigrisCreateProjectResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TigrisCreateProjectResponse) GetCreateProjectResponse() *shared.CreateProjectResponse {
	if o == nil {
		return nil
	}
	return o.CreateProjectResponse
}

func (o *TigrisCreateProjectResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TigrisCreateProjectResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TigrisCreateProjectResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
