// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisDropCollectionRequest struct {
	DropCollectionRequest shared.DropCollectionRequest `request:"mediaType=application/json"`
	// Collection name to delete.
	Collection string `pathParam:"style=simple,explode=false,name=collection"`
	// Project name whose db is under target to delete collection.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *TigrisDropCollectionRequest) GetDropCollectionRequest() shared.DropCollectionRequest {
	if o == nil {
		return shared.DropCollectionRequest{}
	}
	return o.DropCollectionRequest
}

func (o *TigrisDropCollectionRequest) GetCollection() string {
	if o == nil {
		return ""
	}
	return o.Collection
}

func (o *TigrisDropCollectionRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type TigrisDropCollectionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	DropCollectionResponse *shared.DropCollectionResponse
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *TigrisDropCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TigrisDropCollectionResponse) GetDropCollectionResponse() *shared.DropCollectionResponse {
	if o == nil {
		return nil
	}
	return o.DropCollectionResponse
}

func (o *TigrisDropCollectionResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TigrisDropCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TigrisDropCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
