// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisListAppKeysRequest struct {
	// Project name filter
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *TigrisListAppKeysRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type TigrisListAppKeysResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ListAppKeysResponse *shared.ListAppKeysResponse
	// Default error response
	Status *shared.Status
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *TigrisListAppKeysResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TigrisListAppKeysResponse) GetListAppKeysResponse() *shared.ListAppKeysResponse {
	if o == nil {
		return nil
	}
	return o.ListAppKeysResponse
}

func (o *TigrisListAppKeysResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TigrisListAppKeysResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TigrisListAppKeysResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
