// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisImportRequest struct {
	ImportRequest shared.ImportRequest `request:"mediaType=application/json"`
	// Collection name where to import documents.
	Collection string `pathParam:"style=simple,explode=false,name=collection"`
	// Project name whose db is under target to import documents.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisImportResponse struct {
	ContentType string
	// OK
	ImportResponse *shared.ImportResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
