// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisBeginTransactionRequest struct {
	BeginTransactionRequest shared.BeginTransactionRequest `request:"mediaType=application/json"`
	// Project name whose DB this transaction belongs to.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisBeginTransactionResponse struct {
	// OK
	BeginTransactionResponse *shared.BeginTransactionResponse
	ContentType              string
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
