// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisRollbackTransactionRequest struct {
	RollbackTransactionRequest shared.RollbackTransactionRequest `request:"mediaType=application/json"`
	// Project name whose DB this transaction belongs to.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

func (o *TigrisRollbackTransactionRequest) GetRollbackTransactionRequest() shared.RollbackTransactionRequest {
	if o == nil {
		return shared.RollbackTransactionRequest{}
	}
	return o.RollbackTransactionRequest
}

func (o *TigrisRollbackTransactionRequest) GetProject() string {
	if o == nil {
		return ""
	}
	return o.Project
}

type TigrisRollbackTransactionResponse struct {
	ContentType string
	// OK
	RollbackTransactionResponse *shared.RollbackTransactionResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}

func (o *TigrisRollbackTransactionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TigrisRollbackTransactionResponse) GetRollbackTransactionResponse() *shared.RollbackTransactionResponse {
	if o == nil {
		return nil
	}
	return o.RollbackTransactionResponse
}

func (o *TigrisRollbackTransactionResponse) GetStatus() *shared.Status {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TigrisRollbackTransactionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TigrisRollbackTransactionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
