// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisReadRequest struct {
	ReadRequest shared.ReadRequest `request:"mediaType=application/json"`
	// Collection name to read documents from.
	Collection string `pathParam:"style=simple,explode=false,name=collection"`
	// Project name whose db is under target to read documents from.
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisReadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Default error response
	Status *shared.Status
	// OK
	StreamingReadResponse *shared.StreamingReadResponse
}
