// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisRotateAppKeySecretRequest struct {
	RotateAppKeyRequest shared.RotateAppKeyRequest `request:"mediaType=application/json"`
	// project name
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisRotateAppKeySecretResponse struct {
	ContentType string
	// OK
	RotateAppKeyResponse *shared.RotateAppKeyResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
