// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisCreateBranchRequest struct {
	CreateBranchRequest shared.CreateBranchRequest `request:"mediaType=application/json"`
	// Name of the database branch to be created. <p></p>**Note**: `main` is a reserved branch name for primary database and is automatically created with CreateProject
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// Create a database branch in this project
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisCreateBranchResponse struct {
	ContentType string
	// OK
	CreateBranchResponse *shared.CreateBranchResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
