// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisDeleteBranchRequest struct {
	RequestBody map[string]interface{} `request:"mediaType=application/json"`
	// Name of the database branch to delete. <p></p>**Note**: `main` branch cannot be deleted, use DeleteProject instead
	Branch string `pathParam:"style=simple,explode=false,name=branch"`
	// Delete a database branch in this project
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisDeleteBranchResponse struct {
	ContentType string
	// OK
	DeleteBranchResponse *shared.DeleteBranchResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
