// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/tigris-go-sdk/pkg/models/shared"
	"net/http"
)

type TigrisListBranchesRequest struct {
	// List database branches in this project
	Project string `pathParam:"style=simple,explode=false,name=project"`
}

type TigrisListBranchesResponse struct {
	ContentType string
	// OK
	ListBranchesResponse *shared.ListBranchesResponse
	// Default error response
	Status      *shared.Status
	StatusCode  int
	RawResponse *http.Response
}
