// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppKey - An user AppKey
type AppKey struct {
	// Created at
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Created by
	CreatedBy *string `json:"created_by,omitempty"`
	// A human readable app description
	Description *string `json:"description,omitempty"`
	// Generated client id
	ID *string `json:"id,omitempty"`
	// A human readable app name
	Name *string `json:"name,omitempty"`
	// Project it belongs to
	Project *string `json:"project,omitempty"`
	// Generated app secret
	Secret *string `json:"secret,omitempty"`
	// Updated at
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	// Updated by
	UpdatedBy *string `json:"updated_by,omitempty"`
}
