// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AppKey - An user AppKey
type AppKey struct {
	// Created at
	CreatedAt *int64 `json:"created_at,omitempty"`
	// Created by
	CreatedBy *string `json:"created_by,omitempty"`
	// A human readable app description
	Description *string `json:"description,omitempty"`
	// Generated client id
	ID *string `json:"id,omitempty"`
	// A human readable app name
	Name *string `json:"name,omitempty"`
	// Project it belongs to
	Project *string `json:"project,omitempty"`
	// Generated app secret
	Secret *string `json:"secret,omitempty"`
	// Updated at
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	// Updated by
	UpdatedBy *string `json:"updated_by,omitempty"`
}

func (o *AppKey) GetCreatedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *AppKey) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *AppKey) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *AppKey) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AppKey) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AppKey) GetProject() *string {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *AppKey) GetSecret() *string {
	if o == nil {
		return nil
	}
	return o.Secret
}

func (o *AppKey) GetUpdatedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *AppKey) GetUpdatedBy() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedBy
}
