// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BeginTransactionRequest - Start new transaction in project specified by "project".
type BeginTransactionRequest struct {
	// Optionally specify a project branch name to perform operation on
	Branch *string `json:"branch,omitempty"`
	// Options that can be used to modify the transaction semantics.
	Options *TransactionOptions `json:"options,omitempty"`
}
