// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CacheMetadata struct {
	// Cache name
	Name *string `json:"name,omitempty"`
}

func (o *CacheMetadata) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
