// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CollectionInfo struct {
	// Collection name.
	Collection *string                `json:"collection,omitempty"`
	Metadata   map[string]interface{} `json:"metadata,omitempty"`
}
