// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateOrUpdateCollectionResponse - OK
type CreateOrUpdateCollectionResponse struct {
	// A detailed response message.
	Message *string `json:"message,omitempty"`
	// An enum with value set as "created" or "updated"
	Status *string `json:"status,omitempty"`
}
