// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateAppKeyResponse returns created app keys
type CreateAppKeyResponse struct {
	// An user AppKey
	CreatedAppKey *AppKey `json:"created_app_key,omitempty"`
}

func (o *CreateAppKeyResponse) GetCreatedAppKey() *AppKey {
	if o == nil {
		return nil
	}
	return o.CreatedAppKey
}
