// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateAppKeyRequest - Request creation of user app key
type CreateAppKeyRequest struct {
	// A human readable app description
	Description *string `json:"description,omitempty"`
	// A human readable app name
	Name *string `json:"name,omitempty"`
}

func (o *CreateAppKeyRequest) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *CreateAppKeyRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
