// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateNamespaceRequest struct {
	// Optional: unique id
	Code *int64 `json:"code,omitempty"`
	// Optional: unique string id
	ID *string `json:"id,omitempty"`
	// Required: The display name for namespace.
	Name *string `json:"name,omitempty"`
}

func (o *CreateNamespaceRequest) GetCode() *int64 {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *CreateNamespaceRequest) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CreateNamespaceRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
