// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteAppKeyResponse - AppKeys returns the flag to convey if app key was deleted
type DeleteAppKeyResponse struct {
	// status flag for delete operation
	Deleted *bool `json:"deleted,omitempty"`
}
