// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeleteDocumentRequest struct {
	// A list of ids
	Ids []string `json:"ids,omitempty"`
	// The index name of the documents that needs deletion.
	Index *string `json:"index,omitempty"`
	// The project name.
	Project *string `json:"project,omitempty"`
}
