// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeleteIndexRequest struct {
	// index name.
	Name *string `json:"name,omitempty"`
	// Tigris project name.
	Project *string `json:"project,omitempty"`
}

func (o *DeleteIndexRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *DeleteIndexRequest) GetProject() *string {
	if o == nil {
		return nil
	}
	return o.Project
}
