// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeleteByQueryRequest struct {
	// A filter is required to delete matching documents. To delete document by id, you can pass the filter as follows ```{"id": "test"}```
	Filter *string `json:"filter,omitempty"`
	// The index name of the documents that needs deletion.
	Index *string `json:"index,omitempty"`
	// The project name.
	Project *string `json:"project,omitempty"`
}

func (o *DeleteByQueryRequest) GetFilter() *string {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *DeleteByQueryRequest) GetIndex() *string {
	if o == nil {
		return nil
	}
	return o.Index
}

func (o *DeleteByQueryRequest) GetProject() *string {
	if o == nil {
		return nil
	}
	return o.Project
}
