// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteAppKeyRequest - Request deletion of an app key
type DeleteAppKeyRequest struct {
	// app_key id
	ID *string `json:"id,omitempty"`
}
