// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteIndexResponse - OK
type DeleteIndexResponse struct {
	// A detailed response message.
	Message *string `json:"message,omitempty"`
	// An enum with value set as "deleted".
	Status *string `json:"status,omitempty"`
}
