// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeleteIndexResponse struct {
	// A detailed response message.
	Message *string `json:"message,omitempty"`
	// An enum with value set as "deleted".
	Status *string `json:"status,omitempty"`
}

func (o *DeleteIndexResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *DeleteIndexResponse) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
