// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DescribeCollectionRequest struct {
	// Optionally specify a database branch name to perform operation on
	Branch *string `json:"branch,omitempty"`
	// Name of the collection.
	Collection *string `json:"collection,omitempty"`
	// Collection requests modifying options.
	Options *CollectionOptions `json:"options,omitempty"`
	// Project name whose db is under target to get description of its collection.
	Project *string `json:"project,omitempty"`
	// Return schema in the requested format. Format can be JSON, Go, TypeScript, Java. Default is JSON.
	SchemaFormat *string `json:"schema_format,omitempty"`
}

func (o *DescribeCollectionRequest) GetBranch() *string {
	if o == nil {
		return nil
	}
	return o.Branch
}

func (o *DescribeCollectionRequest) GetCollection() *string {
	if o == nil {
		return nil
	}
	return o.Collection
}

func (o *DescribeCollectionRequest) GetOptions() *CollectionOptions {
	if o == nil {
		return nil
	}
	return o.Options
}

func (o *DescribeCollectionRequest) GetProject() *string {
	if o == nil {
		return nil
	}
	return o.Project
}

func (o *DescribeCollectionRequest) GetSchemaFormat() *string {
	if o == nil {
		return nil
	}
	return o.SchemaFormat
}
