// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DescribeNamespacesResponse - OK
type DescribeNamespacesResponse struct {
	Data *DescribeNamespacesData `json:"data,omitempty"`
}

func (o *DescribeNamespacesResponse) GetData() *DescribeNamespacesData {
	if o == nil {
		return nil
	}
	return o.Data
}
