// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DescribeDatabaseResponse - A detailed description of the database and all the associated collections. Description of the collection includes schema details as well.
type DescribeDatabaseResponse struct {
	// List of all the branches in this database
	Branches []string `json:"branches,omitempty"`
	// A detailed description about all the collections. The description returns collection metadata and the schema.
	Collections []CollectionDescription `json:"collections,omitempty"`
	Metadata    *DatabaseMetadata       `json:"metadata,omitempty"`
	// Sum of all the collections sizes present in this database
	Size *int64 `json:"size,omitempty"`
}

func (o *DescribeDatabaseResponse) GetBranches() []string {
	if o == nil {
		return nil
	}
	return o.Branches
}

func (o *DescribeDatabaseResponse) GetCollections() []CollectionDescription {
	if o == nil {
		return nil
	}
	return o.Collections
}

func (o *DescribeDatabaseResponse) GetMetadata() *DatabaseMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *DescribeDatabaseResponse) GetSize() *int64 {
	if o == nil {
		return nil
	}
	return o.Size
}
