// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DocStatus struct {
	// The Error type defines a logical error model
	Error *Error `json:"error,omitempty"`
	// An id of the document.
	ID *string `json:"id,omitempty"`
}
