// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DropCollectionRequest struct {
	// Optionally specify a project branch name to perform operation on
	Branch *string `json:"branch,omitempty"`
	// Collection requests modifying options.
	Options *CollectionOptions `json:"options,omitempty"`
}
