// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DropCollectionResponse - OK
type DropCollectionResponse struct {
	// A detailed response message.
	Message *string `json:"message,omitempty"`
	// An enum with value set as "dropped".
	Status *string `json:"status,omitempty"`
}
