// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ErrorCode - The status code is a short, machine parsable string, which uniquely identifies the error type. Tigris to HTTP code mapping [here](/reference/http-code)
type ErrorCode string

const (
	ErrorCodeOk                 ErrorCode = "OK"
	ErrorCodeCancelled          ErrorCode = "CANCELLED"
	ErrorCodeUnknown            ErrorCode = "UNKNOWN"
	ErrorCodeInvalidArgument    ErrorCode = "INVALID_ARGUMENT"
	ErrorCodeDeadlineExceeded   ErrorCode = "DEADLINE_EXCEEDED"
	ErrorCodeNotFound           ErrorCode = "NOT_FOUND"
	ErrorCodeAlreadyExists      ErrorCode = "ALREADY_EXISTS"
	ErrorCodePermissionDenied   ErrorCode = "PERMISSION_DENIED"
	ErrorCodeResourceExhausted  ErrorCode = "RESOURCE_EXHAUSTED"
	ErrorCodeFailedPrecondition ErrorCode = "FAILED_PRECONDITION"
	ErrorCodeAborted            ErrorCode = "ABORTED"
	ErrorCodeOutOfRange         ErrorCode = "OUT_OF_RANGE"
	ErrorCodeUnimplemented      ErrorCode = "UNIMPLEMENTED"
	ErrorCodeInternal           ErrorCode = "INTERNAL"
	ErrorCodeUnavailable        ErrorCode = "UNAVAILABLE"
	ErrorCodeDataLoss           ErrorCode = "DATA_LOSS"
	ErrorCodeUnauthenticated    ErrorCode = "UNAUTHENTICATED"
	ErrorCodeConflict           ErrorCode = "CONFLICT"
	ErrorCodeBadGateway         ErrorCode = "BAD_GATEWAY"
	ErrorCodeMethodNotAllowed   ErrorCode = "METHOD_NOT_ALLOWED"
)

func (e ErrorCode) ToPointer() *ErrorCode {
	return &e
}

func (e *ErrorCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OK":
		fallthrough
	case "CANCELLED":
		fallthrough
	case "UNKNOWN":
		fallthrough
	case "INVALID_ARGUMENT":
		fallthrough
	case "DEADLINE_EXCEEDED":
		fallthrough
	case "NOT_FOUND":
		fallthrough
	case "ALREADY_EXISTS":
		fallthrough
	case "PERMISSION_DENIED":
		fallthrough
	case "RESOURCE_EXHAUSTED":
		fallthrough
	case "FAILED_PRECONDITION":
		fallthrough
	case "ABORTED":
		fallthrough
	case "OUT_OF_RANGE":
		fallthrough
	case "UNIMPLEMENTED":
		fallthrough
	case "INTERNAL":
		fallthrough
	case "UNAVAILABLE":
		fallthrough
	case "DATA_LOSS":
		fallthrough
	case "UNAUTHENTICATED":
		fallthrough
	case "CONFLICT":
		fallthrough
	case "BAD_GATEWAY":
		fallthrough
	case "METHOD_NOT_ALLOWED":
		*e = ErrorCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorCode: %v", v)
	}
}

// The Error type defines a logical error model
type Error struct {
	// The status code is a short, machine parsable string, which uniquely identifies the error type. Tigris to HTTP code mapping [here](/reference/http-code)
	Code *ErrorCode `json:"code,omitempty"`
	// A developer-facing descriptive error message
	Message *string `json:"message,omitempty"`
}

func (o *Error) GetCode() *ErrorCode {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *Error) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
