// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FacetStats - Additional stats for faceted field
type FacetStats struct {
	// Average of all values in a field. Only available for numeric fields
	Avg *float64 `json:"avg,omitempty"`
	// Total number of values in a field
	Count *int64 `json:"count,omitempty"`
	// Maximum of all values in a field. Only available for numeric fields
	Max *float64 `json:"max,omitempty"`
	// Minimum of all values in a field. Only available for numeric fields
	Min *float64 `json:"min,omitempty"`
	// Sum of all values in a field. Only available for numeric fields
	Sum *float64 `json:"sum,omitempty"`
}
