// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetRTChannelsResponse - OK
type GetRTChannelsResponse struct {
	Channels []ChannelMetadata `json:"channels,omitempty"`
}
