// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetRTChannelResponse struct {
	Channel *string `json:"channel,omitempty"`
}

func (o *GetRTChannelResponse) GetChannel() *string {
	if o == nil {
		return nil
	}
	return o.Channel
}
