// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetResponse - OK
type GetResponse struct {
	// expiration ms
	ExpiresInMs *int64 `json:"expires_in_ms,omitempty"`
	// value
	Value *string `json:"value,omitempty"`
}
