// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetRTChannelsResponse struct {
	Channels []ChannelMetadata `json:"channels,omitempty"`
}

func (o *GetRTChannelsResponse) GetChannels() []ChannelMetadata {
	if o == nil {
		return nil
	}
	return o.Channels
}
