// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetSetResponse - OK
type GetSetResponse struct {
	// A detailed response message.
	Message *string `json:"message,omitempty"`
	// An old value if exists
	OldValue *string `json:"old_value,omitempty"`
	// An enum with value set as "set"
	Status *string `json:"status,omitempty"`
}
