// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GetSetRequest struct {
	// free form byte[] value
	Value *string `json:"value,omitempty"`
}

func (o *GetSetRequest) GetValue() *string {
	if o == nil {
		return nil
	}
	return o.Value
}
