// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type InsertRequestDocuments struct {
}

type InsertRequest struct {
	// Optionally specify a database branch name to perform operation on
	Branch *string `json:"branch,omitempty"`
	// Array of documents to insert. Each document is a JSON object.
	Documents []InsertRequestDocuments `json:"documents,omitempty"`
	// additional options for insert requests.
	Options *InsertRequestOptions `json:"options,omitempty"`
}
