// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListCachesResponse - OK
type ListCachesResponse struct {
	// List of caches metadata
	Caches []CacheMetadata `json:"caches,omitempty"`
}

func (o *ListCachesResponse) GetCaches() []CacheMetadata {
	if o == nil {
		return nil
	}
	return o.Caches
}
