// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListCollectionsResponse - OK
type ListCollectionsResponse struct {
	// List of the collections info in the database.
	Collections []CollectionInfo `json:"collections,omitempty"`
}
