// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListProjectsResponse - OK
type ListProjectsResponse struct {
	// List of the projects.
	Projects []ProjectInfo `json:"projects,omitempty"`
}

func (o *ListProjectsResponse) GetProjects() []ProjectInfo {
	if o == nil {
		return nil
	}
	return o.Projects
}
