// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListCollectionsResponse struct {
	// List of the collections info in the database.
	Collections []CollectionInfo `json:"collections,omitempty"`
}

func (o *ListCollectionsResponse) GetCollections() []CollectionInfo {
	if o == nil {
		return nil
	}
	return o.Collections
}
