// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MessagesResponse - OK
type MessagesResponse struct {
	// ids of the published messages
	Ids []string `json:"ids,omitempty"`
}
