// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MessagesResponse struct {
	// ids of the published messages
	Ids []string `json:"ids,omitempty"`
}

func (o *MessagesResponse) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}
