// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// MetricSeries - Represents series in timeseries based on input query.
type MetricSeries struct {
	DataPoints []DataPoint `json:"dataPoints,omitempty"`
	From       *int64      `json:"from,omitempty"`
	Metric     *string     `json:"metric,omitempty"`
	Scope      *string     `json:"scope,omitempty"`
	To         *int64      `json:"to,omitempty"`
}

func (o *MetricSeries) GetDataPoints() []DataPoint {
	if o == nil {
		return nil
	}
	return o.DataPoints
}

func (o *MetricSeries) GetFrom() *int64 {
	if o == nil {
		return nil
	}
	return o.From
}

func (o *MetricSeries) GetMetric() *string {
	if o == nil {
		return nil
	}
	return o.Metric
}

func (o *MetricSeries) GetScope() *string {
	if o == nil {
		return nil
	}
	return o.Scope
}

func (o *MetricSeries) GetTo() *int64 {
	if o == nil {
		return nil
	}
	return o.To
}
