// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Page - Pagination metadata for SearchResponse
type Page struct {
	// Number representing the current page of results
	Current *int `json:"current,omitempty"`
	// Maximum number of results per page
	Size *int `json:"size,omitempty"`
}
