// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ProjectInfo struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Project name.
	Project *string `json:"project,omitempty"`
}
