// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// QuotaLimitsResponse - Contains current quota limits
type QuotaLimitsResponse struct {
	// Number of allowed read units per second
	ReadUnits *int64 `json:"ReadUnits,omitempty"`
	// Maximum number of bytes allowed to store
	StorageSize *int64 `json:"StorageSize,omitempty"`
	// Number of allowed write units per second
	WriteUnits *int64 `json:"WriteUnits,omitempty"`
}

func (o *QuotaLimitsResponse) GetReadUnits() *int64 {
	if o == nil {
		return nil
	}
	return o.ReadUnits
}

func (o *QuotaLimitsResponse) GetStorageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.StorageSize
}

func (o *QuotaLimitsResponse) GetWriteUnits() *int64 {
	if o == nil {
		return nil
	}
	return o.WriteUnits
}
