// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Data - Object containing the collection document.
type Data struct {
}

type ReadResponse struct {
	// Object containing the collection document.
	Data *Data `json:"data,omitempty"`
	// Has metadata related to the documents stored.
	Metadata *ResponseMetadata `json:"metadata,omitempty"`
	// An internal key, used for pagination.
	ResumeToken *string `json:"resume_token,omitempty"`
}

func (o *ReadResponse) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ReadResponse) GetMetadata() *ResponseMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *ReadResponse) GetResumeToken() *string {
	if o == nil {
		return nil
	}
	return o.ResumeToken
}
