// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ReadMessagesResponse struct {
	Message *Message `json:"message,omitempty"`
}

func (o *ReadMessagesResponse) GetMessage() *Message {
	if o == nil {
		return nil
	}
	return o.Message
}
