// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RotateAppKeyResponse - RotateAppKeyResponse returns the new app key with rotated secret
type RotateAppKeyResponse struct {
	// An user AppKey
	AppKey *AppKey `json:"app_key,omitempty"`
}
