// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SearchHitData - Actual search document
type SearchHitData struct {
}

type SearchHit struct {
	// Actual search document
	Data *SearchHitData `json:"data,omitempty"`
	// Contains metadata related to the search hit, has information about document created_at/updated_at as well.
	Metadata *SearchHitMeta `json:"metadata,omitempty"`
}

func (o *SearchHit) GetData() *SearchHitData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *SearchHit) GetMetadata() *SearchHitMeta {
	if o == nil {
		return nil
	}
	return o.Metadata
}
