// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SearchFacet struct {
	Counts []FacetCount `json:"counts,omitempty"`
	// Additional stats for faceted field
	Stats *FacetStats `json:"stats,omitempty"`
}

func (o *SearchFacet) GetCounts() []FacetCount {
	if o == nil {
		return nil
	}
	return o.Counts
}

func (o *SearchFacet) GetStats() *FacetStats {
	if o == nil {
		return nil
	}
	return o.Stats
}
