// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SetRequest struct {
	// optional - ttl specific to this key in second
	Ex *int64 `json:"ex,omitempty"`
	// set only if the key doesn't exist
	Nx *bool `json:"nx,omitempty"`
	// optional - ttl specific to this key in millisecond
	Px *int64 `json:"px,omitempty"`
	// free form byte[] value
	Value *string `json:"value,omitempty"`
	// set only if the key exist
	Xx *bool `json:"xx,omitempty"`
}
