// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type StreamingSearchResponse struct {
	// The Error type defines a logical error model
	Error *Error `json:"error,omitempty"`
	// Response struct for search
	Result *SearchResponse `json:"result,omitempty"`
}

func (o *StreamingSearchResponse) GetError() *Error {
	if o == nil {
		return nil
	}
	return o.Error
}

func (o *StreamingSearchResponse) GetResult() *SearchResponse {
	if o == nil {
		return nil
	}
	return o.Result
}
