// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateRequestFields - Fields contains set of fields with the values which need to be updated. Should be proper JSON object.
type UpdateRequestFields struct {
}

// UpdateRequestFilter - Update documents which matching specified filter. A filter can simply be key, value where key is the field name and value would be the value for this field. Or a filter can be logical where two or more fields can be logically joined using $or and $and. A few examples of filter: <li> To update a user document where the id has a value 1: ```{"id": 1 }``` <li> To update all the user documents where the key "id" has a value 1 or 2 or 3: `{"$or": [{"id": 1}, {"id": 2}, {"id": 3}]}`
type UpdateRequestFilter struct {
}

type UpdateRequest struct {
	// Optionally specify a database branch name to perform operation on
	Branch *string `json:"branch,omitempty"`
	// Fields contains set of fields with the values which need to be updated. Should be proper JSON object.
	Fields *UpdateRequestFields `json:"fields,omitempty"`
	// Update documents which matching specified filter. A filter can simply be key, value where key is the field name and value would be the value for this field. Or a filter can be logical where two or more fields can be logically joined using $or and $and. A few examples of filter: <li> To update a user document where the id has a value 1: ```{"id": 1 }``` <li> To update all the user documents where the key "id" has a value 1 or 2 or 3: `{"$or": [{"id": 1}, {"id": 2}, {"id": 3}]}`
	Filter *UpdateRequestFilter `json:"filter,omitempty"`
	// Additional options for update requests.
	Options *UpdateRequestOptions `json:"options,omitempty"`
}

func (o *UpdateRequest) GetBranch() *string {
	if o == nil {
		return nil
	}
	return o.Branch
}

func (o *UpdateRequest) GetFields() *UpdateRequestFields {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *UpdateRequest) GetFilter() *UpdateRequestFilter {
	if o == nil {
		return nil
	}
	return o.Filter
}

func (o *UpdateRequest) GetOptions() *UpdateRequestOptions {
	if o == nil {
		return nil
	}
	return o.Options
}
