// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateResponse struct {
	// Has metadata related to the documents stored.
	Metadata *ResponseMetadata `json:"metadata,omitempty"`
	// Returns the number of documents modified.
	ModifiedCount *int `json:"modified_count,omitempty"`
	// an enum with value set as "updated".
	Status *string `json:"status,omitempty"`
}

func (o *UpdateResponse) GetMetadata() *ResponseMetadata {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *UpdateResponse) GetModifiedCount() *int {
	if o == nil {
		return nil
	}
	return o.ModifiedCount
}

func (o *UpdateResponse) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}
