// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type UpdateUserMetadataRequestValue struct {
}

// UpdateUserMetadataRequest - Request update of user metadata
type UpdateUserMetadataRequest struct {
	MetadataKey *string                         `json:"metadataKey,omitempty"`
	Value       *UpdateUserMetadataRequestValue `json:"value,omitempty"`
}
